version: '3.8'

services:
  functious:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_ID=${DISCORD_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - EVENT_JOIN_TOKEN=${EVENT_JOIN_TOKEN}
      - EVENT_LEAVE_TOKEN=${EVENT_LEAVE_TOKEN}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped